### ISSUE TITLE
Implement data model

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/BulletJournal#5]
Once defined with #4, implement the data model with Core Data. 

### Sub-tasks

- [x] Define entities and relationships in Core Data. 
- [x] Add extensions to ˋNSManagedObjectˋ sub classes as needed. 
- [x] ~~Implement a ˋJournalViewControllerDataSourceˋ class for the ˋUIPageViewController that manages creation of pages.~~ (moved to #9)
