### ISSUE TITLE
Drawable page view

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/BulletJournal#6]
Implement the generic view controller to draw log entries. It‘s view should be setup by code, not via storyboard to allow inheritance. 

### Sub-tasks

- [x] Rename view controller to `DrawablePageViewController`.  
- [x] ~~Remove view controller from storyboard.~~ (obsolete)
- [x] ~~Add buttons and canvas in `viewDidLoad`.~~ (obsolete)
